name = "geomont"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "geomont"

[env.staging]
name = "geomont-staging"

# Variabili d'ambiente
[vars]
NODE_ENV = "production"
PORT = "8080"

# Configurazione per rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"