name = "trovageo"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "trovageo"

[env.staging]
name = "trovageo-staging"

# Variabili d'ambiente
[vars]
NODE_ENV = "production"
PORT = "8080"